/**
 * Convenience aliases over the generated `Database` type in ./types.ts.
 *
 * `types.ts` is regenerated by `npm run db:types` and must not be edited by
 * hand — this file wraps it so the rest of the codebase has stable names
 * that survive regeneration.
 */

import type { Database } from "./types";

type Tables = Database["public"]["Tables"];
type Enums = Database["public"]["Enums"];

export type UserRow = Tables["users"]["Row"];
export type UserInsert = Tables["users"]["Insert"];
export type UserUpdate = Tables["users"]["Update"];

export type EventRow = Tables["events"]["Row"];
export type EventInsert = Tables["events"]["Insert"];
export type EventUpdate = Tables["events"]["Update"];

export type EventParticipationRow = Tables["event_participations"]["Row"];
export type EventParticipationInsert = Tables["event_participations"]["Insert"];

export type DonationRow = Tables["donations"]["Row"];
export type DonationInsert = Tables["donations"]["Insert"];

// Enum aliases — mirror DB truth.
// UserRole lives in lib/roles.ts (kept in sync with Enums["user_role"]).
export type EventType = Enums["event_type"];
export type EventStatus = Enums["event_status"];
export type ParticipationStatus = Enums["participation_status"];
export type DonationKind = Enums["donation_kind"];
export type DonationFrequency = Enums["donation_frequency"];
export type DonationStatus = Enums["donation_status"];
